#!/bin/bash

mkdir -p examples/tipping/results

FULLPATH="examples/tipping/results/$1"

echo 'Inferring from lowTips.csv...' | tee $FULLPATH
webppl examples/tipping/src/predicting.wppl --require . --require examples/tipping/ --require webppl-fs -- --data synthetic/lowTips.csv >> $FULLPATH

echo 'Inferring from mediumTips.csv...' | tee -a $FULLPATH
webppl examples/tipping/src/predicting.wppl --require . --require examples/tipping/ --require webppl-fs -- --data synthetic/mediumTips.csv >> $FULLPATH

echo 'Inferring from highTips.csv...' | tee -a $FULLPATH
webppl examples/tipping/src/predicting.wppl --require . --require examples/tipping/ --require webppl-fs -- --data synthetic/highTips.csv >> $FULLPATH

echo "Finished. Results written to: $FULLPATH" | tee -a $FULLPATH